### ISSUE TITLE
Where to get VO for externals?

### ISSUE THREAD

**Issue by davispuh** [RazTools/Audio#3]
Hi,

From https://github.com/Dimbreath/StarRailData we can get `ExcelOutput/VoiceConfig.json` where will be names for externals in `VoicePath` key like
```json
  "103040552": {
    "VoiceID": 103040552,
    "VoicePath": "chapter3_3_firefly_253"
  },
```

But it doesn't match with any External hash so how do you get VO file? Maybe you need to prepend some value to this?

**Comment by Modder4869** [comment]
something like https://gist.github.com/undefined9071/90cd0f6ede44affd2978ef5947b5e14a

**Comment by davispuh** [comment]
Awesome that works, basically we just need to prepend `$LANG/voice/` and append `.wem`.

I did it with this oneliner  
```
$ jq -r 'values[].VoicePath' ExcelOutput/VoiceConfig.json | sort -u | sed 's|^|English/voice/|' | sed 's|$|.wem|'
```
^ that matched ~25.5k out of ~30k so now I understand this :)

Thanks!
